version: '3.7'
services:  
  pg-docker:
    image: postgres:15.4-alpine
    user: root # para dar acesso ao root e não dar erro de salvamento
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: YOURPASSWORD
    ports: 
      - 5433:5432
    volumes: 
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
  pgadmin-docker: 
    image: dpage/pgadmin4     
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: YOURPASSWORD
    ports:
      - 5050:80 
    user: root
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge